### ISSUE TITLE
docker image vproxyio/controller:latest not found

### ISSUE THREAD

**Issue by gzOne2Free** [vproxy-tools/vpctl#8]
When I apply yaml file k8s-vproxy.yaml, the pod of deployment vproxy-gateway can not startup. And the event says: 
`Failed to pull image "vproxyio/controller:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for vproxyio/controller, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

Then I look inti docker hub, in registry vproxyio, it has 14 images but no one named 'controller'.

How can I solve this problem?

**Comment by wkgcass** [comment]
The `vpctl` did some refactor some time ago.  
It used to be a hand written k8s watch client, and now it's refactored using `operator-sdk`.  
I believe some examples are not properly updated.

I'll do a full check and fix this.

---

Also, the `vproxy` project is currently doing `Java 21 Panama` upgrading. I might do some `force push` to `vproxy/dev` branch to keep the commit history clean. If you've cloned that project, you might have to `drop+pull` the `dev` branch again. This upgrading should settle in one or two weeks.

**Comment by wkgcass** [comment]
Now the examples should work without trouble.

If you run into a problem, feel free to re-open this issue.

**Comment by gzOne2Free** [comment]
Hi @wkgcass 
在dockerhub上存在上面提及的缺失的controller镜像之后，镜像缺失的问题解决了，不过现在碰到了另外一个问题：
在gateway容器启动的过程中报以下event，容器启动失败，不断重启。
```
LAST SEEN   TYPE      REASON              OBJECT                                 MESSAGE
22m         Normal    LeaderElection      lease/3c15f24e.vproxy.io               vproxy-gateway-69698d5fd6-dktfb_0022cd1c-0521-4e0f-bdbf-c3b7ba661393 became leader
52m         Normal    Scheduled           pod/vproxy-gateway-69698d5fd6-dktfb    Successfully assigned vproxy-system/vproxy-gateway-69698d5fd6-dktfb to docker-desktop
52m         Normal    Pulling             pod/vproxy-gateway-69698d5fd6-dktfb    Pulling image "vproxyio/controller:latest"
22m         Normal    Pulled              pod/vproxy-gateway-69698d5fd6-dktfb    Successfully pulled image "vproxyio/controller:latest" in 29m17.876684984s (29m17.876695088s including waiting)
22m         Normal    Created             pod/vproxy-gateway-69698d5fd6-dktfb    Created container controller
22m         Normal    Started             pod/vproxy-gateway-69698d5fd6-dktfb    Started container controller
21m         Normal    Pulled              pod/vproxy-gateway-69698d5fd6-dktfb    Container image "vproxyio/vproxy:latest" already present on machine
22m         Normal    Created             pod/vproxy-gateway-69698d5fd6-dktfb    Created container vproxy
22m         Normal    Started             pod/vproxy-gateway-69698d5fd6-dktfb    Started container vproxy
21m         Warning   Unhealthy           pod/vproxy-gateway-69698d5fd6-dktfb    Liveness probe failed: OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
21m         Normal    Killing             pod/vproxy-gateway-69698d5fd6-dktfb    Container vproxy failed liveness probe, will be restarted
2m48s       Warning   BackOff             pod/vproxy-gateway-69698d5fd6-dktfb    Back-off restarting failed container vproxy in pod vproxy-gateway-69698d5fd6-dktfb_vproxy-system(f4d09773-2631-4158-85b2-14dbf21a20a7)
52m         Normal    SuccessfulCreate    replicaset/vproxy-gateway-69698d5fd6   Created pod: vproxy-gateway-69698d5fd6-dktfb
52m         Normal    ScalingReplicaSet   deployment/vproxy-gateway              Scaled up replica set vproxy-gateway-69698d5fd6 to 1
```
重点是这行：
Liveness probe failed: OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
说是找不到curl这个命令，我才是基础OS镜像里没有这个命令？

**Comment by wkgcass** [comment]
因为vproxy的http-controller仅监听127.0.0.1，所以livenessProbe只能用curl来跑  
建议确认下当前的vproxy image sha256，或者重新pull一把`vproxyio/vproxy:latest`试试看  
现在latest的镜像sha256开头是`a63ebf1967e0`

```
        "RepoDigests": [
            "vproxyio/vproxy@sha256:a63ebf1967e0dcb24243c1ea04f6b431263c68f0a2010b8949a8119533c7ed64"
        ],

docker run --rm -it --entrypoint='/bin/bash' vproxyio/vproxy:latest which curl
/usr/bin/curl
```

**Comment by wkgcass** [comment]
不过我刚才发现了另外一个问题，需要调整下yaml。

需要将controller启动参数的`--leader-elect`改为`--leader-elect=false`

部署方案和nginx-ingress-controller比较相似，ngx ingress controller是一个controller只配一个ngx，这里的vproxy-controller也是只配一个vproxy。
